/** Graph vocabulary, independent of TextMate/semantic-token colors.
 * Standard spellings from the language's completion/checker tables. Aliases
 * share labels; user-defined hats are NOT treated as translated keywords.
 * `npm run l10n:extract` merges these messages into the normal VS Code bundles.
 */
export type LabelCategory = "declaration" | "control" | "callable" | "function" | "procedure" | "type" | "value" | "module" | "modifier" | "operator" | "member";
export const HAT_GROUPS: readonly (readonly [string, LabelCategory, string, string])[] = [
    ["let", "declaration", "Variable Definition", "変数定義"],
    ["var", "declaration", "Mutable Variable Definition", "可変変数定義"],
    ["with", "declaration", "Use resource", "リソース使用"],
    ["def", "declaration", "Type definition", "型定義"],
    ["enum", "declaration", "Enumeration", "列挙定義"],
    ["errordef", "declaration", "Error definitions", "エラー定義"],
    ["localerrordef", "declaration", "Local error definitions", "局所エラー定義"],
    ["f", "function", "Function", "関数"],
    ["p", "procedure", "Procedure", "手続き"],
    ["op", "callable", "Operator definition", "演算子定義"],
    ["if", "control", "If", "条件分岐"],
    ["el ei else elif elseif elsif ifel", "control", "Otherwise", "その他の条件"],
    ["for", "control", "For", "対象処理"],
    ["when", "control", "Match", "一致条件"],
    ["other", "control", "Otherwise", "その他の条件"],
    ["while", "control", "While", "条件付き繰り返し"],
    ["until", "control", "Until", "終了条件"],
    ["repeat", "control", "Repeat", "繰り返し"],
    ["do", "control", "Do", "実行"],
    ["in", "control", "In", "各要素"],
    ["from", "control", "From", "開始値"],
    ["to", "control", "Through", "終了値"],
    ["downto", "control", "Down through", "降順の終了値"],
    ["step", "control", "Step", "増減幅"],
    ["prolog prologue", "control", "Before loop", "繰り返し前"],
    ["pre premain", "control", "Before each", "各回の前処理"],
    ["first", "control", "First iteration", "初回処理"],
    ["main", "control", "Loop body", "繰り返し本体"],
    ["last", "control", "Last iteration", "最終回処理"],
    ["epilog epilogue", "control", "After loop", "繰り返し後"],
    ["return", "control", "Return", "戻り値"],
    ["break", "control", "Break", "脱出"],
    ["next skip continue", "control", "Next iteration", "次の繰り返し"],
    ["yield", "control", "Yield", "値を渡して中断"],
    ["_yield", "control", "Suspend", "一時中断"],
    ["await", "control", "Await", "完了待ち"],
    ["defer", "control", "On exit", "終了時処理"],
    ["try", "control", "Propagate error", "エラー伝播"],
    ["catch", "control", "Catch", "エラー捕捉"],
    ["finally", "control", "Finally", "後処理"],
    ["panic", "control", "Raise fatal error", "致命的エラー"],
    ["module", "module", "Module declaration", "モジュール宣言"],
    ["import", "module", "Import", "モジュール読込"],
    ["require", "module", "Require", "ホストモジュール読込"],
    ["pack", "operator", "Pack as table", "テーブルにまとめる"],
    ["public", "modifier", "Public", "公開"],
    ["mutable", "modifier", "Mutable", "変更可能"],
    ["closed", "modifier", "Closed", "閉じ込め"],
    ["fresh", "modifier", "Fresh", "新規生成"],
    ["abstract", "modifier", "Abstract", "抽象"],
    ["override", "modifier", "Override", "上書き定義"],
    ["overload", "modifier", "Overload", "多重定義"],
    ["delegate", "modifier", "Delegate", "委譲"],
    ["box", "declaration", "Mutable box", "可変ボックス"],
    ["constbox", "declaration", "Constant box", "不変ボックス"],
    ["Box", "type", "Box type", "可変ボックス型"],
    ["ConstBox", "type", "Constant box type", "不変ボックス型"],
    ["number int float", "type", "Number", "数値"],
    ["string", "type", "Text", "文字列"],
    ["bool", "type", "Boolean", "真偽値"],
    ["any", "type", "Any type", "任意の型"],
    ["error", "type", "Error", "エラー"],
    ["localerror", "type", "Local error", "局所エラー"],
    ["t", "type", "Table type", "テーブル型"],
    ["c", "type", "Coroutine type", "コルーチン型"],
    ["Self", "type", "Enclosing type", "自身の型"],
    ["ReturnType", "type", "Return type", "戻り値の型"],
    ["nil", "value", "No value", "値なし"],
    ["true", "value", "True", "真"],
    ["false", "value", "False", "偽"],
    ["self", "value", "Self", "自身"],
    ["this", "value", "Current subroutine", "自身の処理"],
    ["it", "value", "Current item", "処理対象"],
    ["super", "value", "Base definition", "基底定義"],
    ["L", "value", "Language environment", "言語環境"],
    ["_", "value", "Discard", "破棄"],
    ["and", "operator", "And", "かつ"],
    ["or", "operator", "Or", "または"],
    ["is", "operator", "Same instance", "同一の値"],
    ["fits", "operator", "Fits type", "型に適合"],
    ["as", "operator", "As type", "型指定"],
    ["typeof", "operator", "Type of", "型を取得"],
    ["id", "operator", "Identifier", "識別子"],
    ["width", "modifier", "Width", "幅"],
    ["autowidth", "modifier", "Automatic width", "自動幅"],
    ["abs", "member", "Absolute value", "絶対値"],
    ["at get", "member", "Get element", "要素取得"],
    ["cause", "member", "Error cause", "エラー原因"],
    ["ceil", "member", "Round up", "切り上げ"],
    ["clamp", "member", "Limit to range", "範囲内に制限"],
    ["clear", "member", "Clear", "全削除"],
    ["clone", "member", "Copy", "複製"],
    ["contains", "member", "Contains", "含む"],
    ["count size", "member", "Element count", "要素数"],
    ["dispose", "member", "Release resource", "リソース解放"],
    ["done", "member", "Finished", "完了済み"],
    ["eq", "member", "Equal", "等しい"],
    ["extend", "member", "Extend", "要素追加"],
    ["find", "member", "Find", "検索"],
    ["findall", "member", "Find all", "全件検索"],
    ["floor", "member", "Round down", "切り下げ"],
    ["indexof", "member", "Find position", "位置を検索"],
    ["insert", "member", "Insert", "挿入"],
    ["iterate", "member", "Iterate", "走査"],
    ["join", "member", "Join", "連結"],
    ["keys", "member", "Keys", "キー一覧"],
    ["len length", "member", "Length", "長さ"],
    ["message", "member", "Error message", "エラーメッセージ"],
    ["move", "member", "Move", "移動"],
    ["pop", "member", "Remove last", "末尾を取り出す"],
    ["push", "member", "Append", "末尾に追加"],
    ["remove", "member", "Remove", "削除"],
    ["replace", "member", "Replace", "置換"],
    ["resume", "member", "Resume", "再開"],
    ["reverse", "member", "Reverse", "逆順"],
    ["round", "member", "Round", "丸める"],
    ["set", "member", "Set element", "要素設定"],
    ["sign", "member", "Sign", "符号"],
    ["slice", "member", "Slice", "範囲抽出"],
    ["sort", "member", "Sort", "並べ替え"],
    ["split", "member", "Split", "分割"],
    ["stablesort", "member", "Stable sort", "安定並べ替え"],
    ["start", "member", "Start", "開始"],
    ["started", "member", "Started", "開始済み"],
    ["sub substr substring", "member", "Substring", "部分文字列"],
    ["tolower", "member", "Lowercase", "小文字に変換"],
    ["tonumber", "member", "To number", "数値に変換"],
    ["tostring", "member", "To text", "文字列に変換"],
    ["toupper", "member", "Uppercase", "大文字に変換"],
    ["value", "member", "Value", "値"],
    ["values", "member", "Values", "値一覧"],
];
export const HATS = Object.fromEntries(HAT_GROUPS.flatMap(([words, category, text]) =>
    words.split(" ").map(word => [word, { category, text }])));
